# version: 4

language: scala
scala:
  - 2.11.7

cache:
  - apt

before_install: cd tests

install:
  - pip install enum34
  - gem install rspec
  - npm install mocha iconv-lite

before_script: cd tests

script:
  - ./compile-all
  - ./run-cpp_stl
  - ./run-java
  - ./run-javascript
  - ./run-python
  - ./run-ruby
