# version: 5

# Use Ubuntu Trusty 14.04 image; unfortunately, it requires "sudo: true"
# and thus is very slow :(
dist: trusty
sudo: true

language: scala
scala:
  - 2.11.7

php:
  - 7.0

cache:
  - apt

addons:
  apt:
    sources:
      - mono
    packages:
      - libboost-test-dev
      - ca-certificates-mono
      - mono-xbuild
      - mono-mcs
      - mono-devel
      - nuget

before_install:
  - cd tests

install:
  # Python
  - pip install --user enum34
  - pip install --user unittest-xml-reporting

  # Ruby
  - gem install rspec

  # JavaScript
  - nvm install 5
  - nvm use 5
  - npm install mocha iconv-lite

  # Java: poor man's maven implementation in 3 lines :)
  - mkdir -p "$HOME/.m2/repository/org/testng/testng/6.9.10" "$HOME/.m2/repository/com/beust/jcommander/1.48"
  - wget -O "$HOME/.m2/repository/org/testng/testng/6.9.10/testng-6.9.10.jar" http://jcenter.bintray.com/org/testng/testng/6.9.10/testng-6.9.10.jar
  - wget -O "$HOME/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar" http://jcenter.bintray.com/com/beust/jcommander/1.48/jcommander-1.48.jar

  # C#
  - mono --version
  - nuget restore spec/csharp/kaitai_struct_csharp_tests.sln

  # PHP: newer PHPUnit, as the one in the repos is very old
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit
  - phpunit --version

script:
  - ./build-compiler
  - ./translator-tests || true
  - ./build-formats
  - ./run-all
  - ../update-ci-status
