# version: 3

language: scala
scala:
  - 2.11.7

addons:
  apt:
    packages:
    - python-enum34
    - nodejs

cache:
  - apt

install:
  - gem install rspec

before_script: cd tests

script:
  - ./compile-all
  - ./run-cpp_stl
  - ./run-java
  - ./run-javascript
  - ./run-python
  - ./run-ruby
