# version: 5

# Use Ubuntu Trusty 14.04 image; unfortunately, it requires "sudo: true"
# and thus is very slow :(
dist: trusty
sudo: true

language: scala
scala:
  - 2.11.7

cache:
  - apt

addons:
  apt:
    packages:
      - libboost-test-dev

before_install:
  # Add extra mono repository: we need mono 4, and, unfortunately, trusty package is mono 3.2.8+dfsg-4ubuntu1.1
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update -q
  - sudo apt-get install ca-certificates-mono mono-xbuild nuget

  - cd tests

install:
  # Python
  - pip install --user enum34
  - pip install --user unittest-xml-reporting

  # Ruby
  - gem install rspec

  # JavaScript
  - nvm install 5
  - nvm use 5
  - npm install mocha iconv-lite

  # Java: poor man's maven implementation in 3 lines :)
  - mkdir -p "$HOME/.m2/repository/org/testng/testng/6.9.10" "$HOME/.m2/repository/com/beust/jcommander/1.48"
  - wget -O "$HOME/.m2/repository/org/testng/testng/6.9.10/testng-6.9.10.jar" http://jcenter.bintray.com/org/testng/testng/6.9.10/testng-6.9.10.jar
  - wget -O "$HOME/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar" http://jcenter.bintray.com/com/beust/jcommander/1.48/jcommander-1.48.jar

  # C#
  - mono --version
  - nuget restore spec/csharp/kaitai_struct_csharp_tests.sln

script:
  - ./compile-all
  - ./run-all
  - ../update-ci-status
